Parameters:
  ImageUri:
    Type: String

Resources:
  HelloWorldDockerLambdaContainer1:
      Type: AWS::Lambda::Function
      Properties:
        FunctionName: hello-world-lambda-docker-container-1
        Role: arn:aws:iam::132502993358:role/lambda-full-access
        PackageType: Image
        Code:
          ImageUri: !Ref ImageUri
        Timeout: 30
        MemorySize: 512
        ImageConfig:
          Command: ["lambda-function.handler"]
  
  HelloWorldDockerLambdaContainer2:
      Type: AWS::Lambda::Function
      Properties:
        FunctionName: hello-world-lambda-docker-container-2
        Role: arn:aws:iam::132502993358:role/lambda-full-access
        PackageType: Image
        Code:
          ImageUri: !Ref ImageUri
        Timeout: 30
        MemorySize: 512
        ImageConfig:
          Command: ["module2.lambda-function2.handler"]
          
  HelloWorldDockerLambdaContainer3:
      Type: AWS::Lambda::Function
      Properties:
        FunctionName: hello-world-lambda-docker-container-3
        Role: arn:aws:iam::132502993358:role/lambda-full-access
        PackageType: Image
        Code:
          ImageUri: !Ref ImageUri
        Timeout: 30
        MemorySize: 512
        ImageConfig:
          Command: ["module3.lambda-function3.handler"]
  
  HelloWorldDockerLambdaContainer4:
      Type: AWS::Lambda::Function
      Properties:
        FunctionName: hello-world-lambda-docker-container-4
        Role: arn:aws:iam::132502993358:role/lambda-full-access
        PackageType: Image
        Code:
          ImageUri: !Ref ImageUri
        Timeout: 30
        MemorySize: 512
        ImageConfig:
          Command: ["module2.inner_module.lambda-function4.handler"]


Outputs:
  LambdaFunctionContainerName:
    Description: Name of the Lambda function
    Value: !Ref  HelloWorldDockerLambdaContainer1
  LambdaFunctionContainerArn:
    Description: Latest published Lambda Layer version ARN
    Value: !GetAtt  HelloWorldDockerLambdaContainer1.Arn
